Repository logos-co/nomos, pull requests merged in 2023-10, with the labels that each got.

#443 Add a second mempool for DA certificates
  nodes/nomos-node/src/bridges/mod.rs
  nodes/nomos-node/src/lib.rs
  nodes/nomos-node/src/main.rs
  nomos-services/consensus/src/lib.rs
Labels: da

#446 Remove waku from the codebase
  .github/workflows/build-test.yml
  .github/workflows/codecov.yml
  Dockerfile
  ci/Dockerfile
  ci/Jenkinsfile.nightly.integration
  ci/Jenkinsfile.prs.linux
  ci/Jenkinsfile.prs.macos
  nodes/nomos-node/README.md
  nomos-services/consensus/Cargo.toml
  nomos-services/consensus/src/network/adapters/mod.rs
  nomos-services/consensus/src/network/adapters/waku.rs
  nomos-services/mempool/Cargo.toml
  nomos-services/mempool/src/network/adapters/mod.rs
  nomos-services/mempool/src/network/adapters/waku.rs
  nomos-services/network/Cargo.toml
  nomos-services/network/src/backends/mod.rs
  nomos-services/network/src/backends/waku.rs
  testnet/Dockerfile
  tests/Cargo.toml
  tests/src/nodes/nomos.rs
Labels: enhancement

#449 Add mempool status API
  nodes/nomos-node/src/bridges/mod.rs
  nodes/nomos-node/src/main.rs
  nomos-services/mempool/src/backend/mockpool.rs
  nomos-services/mempool/src/backend/mod.rs
  nomos-services/mempool/src/lib.rs
Labels: Mempool

#450 Send certificate to node after dissemination + tests
  nodes/nomos-node/src/bridges/mod.rs
  nomos-cli/Cargo.toml
  nomos-cli/src/cmds/disseminate/mod.rs
  nomos-services/mempool/src/lib.rs
  tests/Cargo.toml
  tests/src/lib.rs
  tests/src/nodes/mod.rs
  tests/src/nodes/nomos.rs
  tests/src/tests/cli.rs
Labels: da

#426 Make threshold configurable for TreeOverlay
  consensus-engine/src/overlay/flat_overlay.rs
  consensus-engine/src/overlay/mod.rs
  consensus-engine/src/overlay/threshold.rs
  consensus-engine/src/overlay/tree_overlay/overlay.rs
  simulations/src/bin/app/overlay_node.rs
  tests/src/nodes/nomos.rs
Labels: testing

#442 Modified test, so that all nodes don’t all connect to the first node only
  tests/src/lib.rs
  tests/src/nodes/mixnode.rs
  tests/src/nodes/nomos.rs
  tests/src/tests/happy.rs
  tests/src/tests/unhappy.rs
Labels: network, testing

#415 Nomos node tree overlay
  consensus-engine/src/overlay/flat_overlay.rs
  consensus-engine/src/overlay/mod.rs
  consensus-engine/src/overlay/threshold.rs
  consensus-engine/src/overlay/tree_overlay/overlay.rs
  nodes/nomos-node/src/config.rs
  nodes/nomos-node/src/lib.rs
  nomos-services/consensus/src/lib.rs
  nomos-services/consensus/src/tally/happy.rs
  simulations/src/bin/app/overlay_node.rs
  tests/Cargo.toml
  tests/src/lib.rs
  tests/src/nodes/mixnode.rs
  tests/src/nodes/nomos.rs
  tests/src/tests/cli.rs
  tests/src/tests/happy.rs
  tests/src/tests/unhappy.rs
Labels: node

#423 Nomos node config
  mixnet/client/src/config.rs
  nodes/nomos-node/config.yaml
  testnet/config.yaml
Labels: enhancement, node

#452 Fix clippy and check warnings on released rust 1.73
  consensus-engine/src/overlay/random_beacon.rs
  consensus-engine/tests/fuzz/ref_state.rs
  nomos-da/full-replication/Cargo.toml
  nomos-services/consensus/src/network/adapters/mock.rs
  nomos-services/data-availability/src/lib.rs
  nomos-services/metrics/src/lib.rs
  nomos-services/network/src/backends/mock.rs
  nomos-services/storage/Cargo.toml
  nomos-services/storage/src/backends/sled.rs
  tests/src/tests/mixnet.rs
Labels: enhancement

#451 Finish the skeleton of the api for nomos-node
  Cargo.toml
  nomos-http-api/Cargo.toml
  nomos-http-api/src/lib.rs
  nomos-http-api/tests/todo.rs
Labels: enhancement

#455 Use specific revision on overwatch
  nodes/mixnode/Cargo.toml
  nodes/nomos-node/Cargo.toml
  nomos-cli/Cargo.toml
  nomos-http-api/Cargo.toml
  nomos-services/consensus/Cargo.toml
  nomos-services/data-availability/Cargo.toml
  nomos-services/http/Cargo.toml
  nomos-services/log/Cargo.toml
  nomos-services/mempool/Cargo.toml
  nomos-services/metrics/Cargo.toml
  nomos-services/network/Cargo.toml
  nomos-services/storage/Cargo.toml
  tests/Cargo.toml
Labels: dependencies

#453 Add API to return DA blobs
  nomos-services/data-availability/src/backend/memory_cache.rs
  nomos-services/data-availability/src/backend/mod.rs
  nomos-services/data-availability/src/lib.rs
Labels: da

#454 Make libp2p gossipsub config configurable
  nomos-libp2p/src/config.rs
  nomos-libp2p/src/lib.rs
Labels: network

#460 Dns or socket address for mixnet node config
  mixnet/topology/src/lib.rs
Labels: mixnet, testnet

#458 test(unhappy): mask `sender` when comparing timeout_qcs
  tests/src/tests/unhappy.rs
Labels: testing

#463 Add serde default for `gossipsub::Config`
  nomos-libp2p/src/config.rs
Labels: network

#464 Save safe blocks contents to storage
  nodes/nomos-node/Cargo.toml
  nodes/nomos-node/src/lib.rs
  nodes/nomos-node/src/main.rs
  nomos-services/consensus/Cargo.toml
  nomos-services/consensus/src/lib.rs
  nomos-services/storage/src/backends/sled.rs
Labels: testnet

#462 Add default for `MixnetClientConfig::connection_pool_size`
  mixnet/client/Cargo.toml
  mixnet/client/src/config.rs
  mixnet/topology/src/lib.rs
Labels: mixnet

#470 Update libp2p breaking dep
  nomos-libp2p/Cargo.toml
  nomos-libp2p/src/config.rs
  nomos-libp2p/src/lib.rs
Labels: enhancement

#465 axum backend for new http api
  nomos-http-api/Cargo.toml
  nomos-http-api/src/http/backend/axum.rs
  nomos-http-api/src/http/backend/mod.rs
  nomos-http-api/src/http/mod.rs
  nomos-http-api/src/lib.rs
  nomos-http-api/tests/todo.rs
Labels: enhancement

#461 Extract nomos-cli da stuff into shared module
  nomos-cli/Cargo.toml
  nomos-cli/src/cmds/disseminate/mod.rs
  nomos-cli/src/da/mod.rs
  nomos-cli/src/lib.rs
  tests/src/tests/cli.rs
Labels: da

#477 Add API to revieve DA blobs
  nodes/nomos-node/src/bridges/mod.rs
  nodes/nomos-node/src/lib.rs
  nodes/nomos-node/src/main.rs
  nomos-services/data-availability/src/lib.rs
Labels: da

#457 Lifecycle update and implementations
  nodes/mixnode/Cargo.toml
  nodes/nomos-node/Cargo.toml
  nomos-cli/Cargo.toml
  nomos-http-api/Cargo.toml
  nomos-services/consensus/Cargo.toml
  nomos-services/consensus/src/lib.rs
  nomos-services/data-availability/Cargo.toml
  nomos-services/data-availability/src/lib.rs
  nomos-services/http/Cargo.toml
  nomos-services/log/Cargo.toml
  nomos-services/log/src/lib.rs
  nomos-services/mempool/Cargo.toml
  nomos-services/mempool/src/lib.rs
  nomos-services/metrics/Cargo.toml
  nomos-services/metrics/src/lib.rs
  nomos-services/network/Cargo.toml
  nomos-services/network/src/lib.rs
  nomos-services/storage/Cargo.toml
  nomos-services/storage/src/lib.rs
  tests/Cargo.toml
Labels: refactor

#473 Storage api
  nodes/nomos-node/src/bridges/mod.rs
  nodes/nomos-node/src/main.rs
  nomos-services/storage/src/lib.rs
  tests/src/nodes/nomos.rs
  tests/src/tests/happy.rs
Labels: da

#478 Human serde committeeid
  consensus-engine/src/types/committee.rs
  nomos-utils/src/lib.rs
Labels: enhancement

#468 Humanize array ser/deser
  Cargo.toml
  consensus-engine/Cargo.toml
  consensus-engine/src/types/block_id.rs
  consensus-engine/src/types/committee.rs
  consensus-engine/src/types/node_id.rs
  nomos-services/consensus/src/lib.rs
  nomos-utils/Cargo.toml
  nomos-utils/src/lib.rs
Labels: enhancement

#479 Simulations overlay topo info
  simulations/Cargo.toml
  simulations/src/bin/app/main.rs
  simulations/src/bin/app/overlay_node.rs
  simulations/src/node/dummy.rs
  simulations/src/node/mod.rs
  simulations/src/overlay/mod.rs
  simulations/src/overlay/overlay_info.rs
  simulations/src/overlay/tests/flat.rs
  simulations/src/overlay/tests/mod.rs
  simulations/src/overlay/tests/tree.rs
  simulations/src/runner/sync_runner.rs
Labels: simulation

#486 Allow deprecated type in Swarm
  nomos-libp2p/src/lib.rs
  nomos-services/network/src/backends/libp2p/swarm.rs
Labels: ci

#484 CI: Integration tests report
  ci/Dockerfile
  ci/Jenkinsfile.nightly.integration
Labels: ci

#483 Optional network capacity in simulations
  simulations/src/bin/app/main.rs
  simulations/src/network/mod.rs
  simulations/src/node/dummy.rs
  simulations/src/runner/sync_runner.rs
  simulations/src/settings.rs
Labels: simulation

#480 Add Sigkill handling to node binary
  Cargo.toml
  nodes/nomos-node/Cargo.toml
  nodes/nomos-node/src/lib.rs
  nodes/nomos-node/src/main.rs
  nomos-services/system-sig/Cargo.toml
  nomos-services/system-sig/src/lib.rs
Labels: node

#471 Configure supermajority threshold via envvars
  .env.example
  compose.yml
  nodes/nomos-node/config.yaml
  nodes/nomos-node/src/config.rs
Labels: enhancement, node

#485 Remove block contents from mempool
  nomos-core/src/da/attestation/mod.rs
  nomos-core/src/da/certificate/mod.rs
  nomos-da/full-replication/src/lib.rs
  nomos-services/consensus/src/lib.rs
Labels: Mempool, node

#482 Docker compose consensus layer config
  compose.yml
  testnet/scripts/consensus_node_list.sh
  testnet/scripts/node_key_from_id.sh
  testnet/scripts/register_node.sh
  testnet/scripts/run_bootstrap_node.sh
  testnet/scripts/run_nomos_node.sh
Labels: testnet

#493 Add DA utilities to nomos-cli
  nomos-cli/Cargo.toml
  nomos-cli/src/cmds/disseminate/mod.rs
  nomos-cli/src/da/disseminate.rs
  nomos-cli/src/da/mod.rs
  nomos-cli/src/da/retrieve.rs
  tests/src/tests/cli.rs
Labels: da

#466 Metrics api
  Cargo.toml
  consensus-engine/Cargo.toml
  consensus-engine/src/lib.rs
  consensus-engine/src/types/block_id.rs
  nodes/nomos-node-api/Cargo.toml
  nodes/nomos-node-api/src/http/backend/axum.rs
  nodes/nomos-node-api/src/http/backend/mod.rs
  nodes/nomos-node-api/src/http/cl.rs
  nodes/nomos-node-api/src/http/da.rs
  nodes/nomos-node-api/src/http/mod.rs
  nodes/nomos-node-api/src/lib.rs
  nodes/nomos-node-api/tests/todo.rs
  nomos-da/full-replication/Cargo.toml
  nomos-da/full-replication/src/lib.rs
  nomos-http-api/src/http/backend/axum.rs
  nomos-http-api/src/http/mod.rs
  nomos-services/mempool/Cargo.toml
  nomos-services/mempool/src/backend/mod.rs
  nomos-services/mempool/src/lib.rs
Labels: enhancement

#494 Increase the 20-view timeout of happy integration tests
  tests/src/tests/happy.rs
Labels: testing

#481 Fix typos
  consensus-engine/README.md
  consensus-engine/src/types/block_id.rs
  nodes/nomos-node/README.md
  simulations/src/network/mod.rs
  simulations/src/node/dummy.rs
  tests/src/tests/unhappy.rs
Labels: documentation
