Repository logos-co/nomos, pull requests merged in 2023-09, with the labels that each got.

#363 Prevent mixnet tests from running forever
  tests/Cargo.toml
  tests/src/tests/mixnet.rs
Labels: mixnet

#362 Use random delay when sending msgs to mixnet
  nomos-services/network/src/backends/libp2p.rs
  tests/src/nodes/nomos.rs
Labels: mixnet

#367 GH Actions: Fix Windows build
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: ci

#366 GH Actions: Codecov
  .github/workflows/codecov.yml
Labels: ci

#369 Add missing strategy and target
  .github/workflows/master.yml
Labels: ci

#343 Fix run output fd
  mixnet/client/Cargo.toml
  mixnet/client/src/config.rs
  mixnet/client/src/lib.rs
  mixnet/client/src/receiver.rs
  mixnet/client/src/sender.rs
  mixnet/node/Cargo.toml
  mixnet/node/src/config.rs
  mixnet/node/src/lib.rs
  mixnet/protocol/src/lib.rs
  mixnet/topology/src/lib.rs
  mixnet/util/Cargo.toml
  mixnet/util/src/lib.rs
  tests/src/nodes/mixnode.rs
  tests/src/nodes/nomos.rs
  tests/src/tests/mixnet.rs
Labels: mixnet

#368 Block refactor
  nodes/nomos-node/src/blob.rs
  nodes/nomos-node/src/lib.rs
  nomos-core/src/block.rs
  nomos-services/consensus/src/committee_membership/mod.rs
  nomos-services/consensus/src/leader_selection/mod.rs
  nomos-services/consensus/src/lib.rs
  simulations/src/bin/app/overlay_node.rs
  simulations/src/node/carnot/event_builder.rs
  simulations/src/node/carnot/mod.rs
Labels: refactor, Block

#372 Make mixnode handle bodies coming from the same source concurrently
  mixnet/node/src/lib.rs
Labels: mixnet

#373 Fix MutexGuard across await
  mixnet/node/src/lib.rs
  mixnet/util/src/lib.rs
Labels: mixnet

#376 Initial DA service sketch
  Cargo.toml
  nomos-services/data-availability/Cargo.toml
  nomos-services/data-availability/src/backend/mod.rs
  nomos-services/data-availability/src/lib.rs
  nomos-services/data-availability/src/network/mod.rs
Labels: node

#374 Remove unused functions from mixnet connpool
  mixnet/util/src/lib.rs
Labels: mixnet

#375 Mixnet benchmark
  tests/Cargo.toml
  tests/src/benches/mixnet.rs
Labels: mixnet

#381 Da service backend
  nomos-core/src/blob/mod.rs
  nomos-core/src/lib.rs
  nomos-services/data-availability/Cargo.toml
  nomos-services/data-availability/src/backend/memory_cache.rs
  nomos-services/data-availability/src/backend/mod.rs
  nomos-services/data-availability/src/lib.rs
  nomos-services/data-availability/src/network/mod.rs
Labels: da

#384 Da service network
  nomos-services/data-availability/Cargo.toml
  nomos-services/data-availability/src/network/adapters/libp2p.rs
  nomos-services/data-availability/src/network/adapters/mod.rs
  nomos-services/data-availability/src/network/mod.rs
Labels: da

#385 Simulations: make polars dependancy optional
  .github/workflows/master.yml
  .github/workflows/pr.yml
  simulations/Cargo.toml
  simulations/src/bin/app/main.rs
  simulations/src/bin/app/overlay_node.rs
  simulations/src/node/carnot/timeout.rs
  simulations/src/streaming/mod.rs
Labels: ci

#389 GH Actions: Remove codecov token
  .github/workflows/codecov.yml
Labels: ci

#382 Node envconfig
  nodes/nomos-node/config.yaml
  nodes/nomos-node/src/config.rs
  nodes/nomos-node/src/lib.rs
  nodes/nomos-node/src/main.rs
Labels: node

#390 Da nomos core
  Cargo.toml
  nomos-core/src/da/attestation/mod.rs
  nomos-core/src/da/blob/mod.rs
  nomos-core/src/da/certificate/mod.rs
  nomos-core/src/da/mod.rs
  nomos-core/src/lib.rs
  nomos-da/kzg/Cargo.toml
  nomos-da/kzg/benches/nomos_kzg.rs
  nomos-da/kzg/src/dynamic_kzg.rs
  nomos-da/kzg/src/lib.rs
  nomos-da/kzg/src/types.rs
  nomos-da/reed-solomon/Cargo.toml
  nomos-da/reed-solomon/src/lib.rs
  nomos-services/data-availability/src/backend/memory_cache.rs
  nomos-services/data-availability/src/backend/mod.rs
  nomos-services/data-availability/src/lib.rs
Labels: da

#392 Da service compiling fixes
  nomos-services/data-availability/Cargo.toml
  nomos-services/data-availability/src/network/adapters/libp2p.rs
Labels: bug, da

#393 Simplify mixnet topology
  mixnet/node/src/lib.rs
  mixnet/topology/src/lib.rs
  nodes/nomos-node/config.yaml
  tests/src/nodes/mixnode.rs
  tests/src/tests/mixnet.rs
Labels: mixnet

#394 Simplify bytes and duration range ser/de
  mixnet/topology/Cargo.toml
  mixnet/topology/src/lib.rs
  nodes/nomos-node/config.yaml
  nomos-services/network/Cargo.toml
  nomos-services/network/src/backends/libp2p.rs
Labels: enhancement, mixnet

#396 Add full replication implementation for DA
  Cargo.toml
  nomos-da/full-replication/Cargo.toml
  nomos-da/full-replication/src/lib.rs
Labels: da

#399 Remove failed deserialization error message
  nomos-services/data-availability/src/network/adapters/libp2p.rs
Labels: bug

#316 Mixnet PoC base branch
  Cargo.toml
  mixnet/client/Cargo.toml
  mixnet/client/src/config.rs
  mixnet/client/src/lib.rs
  mixnet/client/src/receiver.rs
  mixnet/client/src/sender.rs
  mixnet/node/Cargo.toml
  mixnet/node/src/client_notifier.rs
  mixnet/node/src/config.rs
  mixnet/node/src/lib.rs
  mixnet/protocol/Cargo.toml
  mixnet/protocol/src/lib.rs
  mixnet/topology/Cargo.toml
  mixnet/topology/src/lib.rs
  mixnet/util/Cargo.toml
  mixnet/util/src/lib.rs
  nodes/mixnode/Cargo.toml
  nodes/mixnode/config.yaml
  nodes/mixnode/src/lib.rs
  nodes/mixnode/src/main.rs
  nodes/mixnode/src/services/mixnet.rs
  nodes/mixnode/src/services/mod.rs
  nodes/nomos-node/config.yaml
  nodes/nomos-node/src/config.rs
  nomos-core/Cargo.toml
  nomos-core/src/tx/mock.rs
  nomos-services/consensus/src/network/adapters/libp2p.rs
  nomos-services/mempool/Cargo.toml
  nomos-services/mempool/src/network/adapters/mock.rs
  nomos-services/mempool/tests/mock.rs
  nomos-services/network/Cargo.toml
  nomos-services/network/src/backends/libp2p.rs
  nomos-services/network/src/lib.rs
  tests/Cargo.toml
  tests/src/benches/mixnet.rs
  tests/src/lib.rs
  tests/src/nodes/mixnode.rs
  tests/src/nodes/mod.rs
  tests/src/nodes/nomos.rs
  tests/src/tests/happy.rs
  tests/src/tests/mixnet.rs
  tests/src/tests/unhappy.rs
Labels: mixnet

#402 Simulation branch with one committee fix
  consensus-engine/src/overlay/branch_overlay.rs
  consensus-engine/src/overlay/mod.rs
Labels: simulation

#401 Block building core
  nomos-core/src/block/builder.rs
  nomos-core/src/block/mod.rs
  nomos-core/src/da/blob/mod.rs
  nomos-core/src/da/blob/select.rs
  nomos-core/src/lib.rs
  nomos-core/src/tx/mod.rs
  nomos-core/src/tx/select.rs
  nomos-core/src/utils/mod.rs
  nomos-core/src/utils/select.rs
  nomos-services/consensus/src/lib.rs
  simulations/src/bin/app/main.rs
  simulations/src/node/carnot/mod.rs
Labels: Tx, Block, blob

#407 Remove unused fountain codes
  nodes/nomos-node/src/lib.rs
  nomos-core/src/fountain/mock.rs
  nomos-core/src/fountain/mod.rs
  nomos-core/src/fountain/raptorq.rs
  nomos-core/src/lib.rs
  nomos-services/consensus/src/lib.rs
  nomos-services/consensus/src/network/adapters/libp2p.rs
  nomos-services/consensus/src/network/adapters/mock.rs
  nomos-services/consensus/src/network/adapters/waku.rs
  nomos-services/consensus/src/network/messages.rs
  nomos-services/consensus/src/network/mod.rs
  simulations/src/node/carnot/event_builder.rs
  simulations/src/node/carnot/messages.rs
  simulations/src/node/carnot/mod.rs
  tests/src/nodes/nomos.rs
Labels: refactor

#403 Change default network backend to libp2p
  nodes/nomos-node/Cargo.toml
Labels: network

#408 Add mixnet usage docs
  mixnet/README.md
  nodes/mixnode/README.md
  nodes/mixnode/config.yaml
  nodes/nomos-node/README.md
  nodes/nomos-node/config.yaml
Labels: mixnet

#409 Disable codecov annotations
  .codecov.yml
  .github/workflows/codecov.yml
Labels: ci

#410 Retry connecting with initial peers
  nodes/nomos-node/src/config.rs
  nomos-libp2p/src/lib.rs
  nomos-services/network/src/backends/libp2p.rs
  tests/src/nodes/nomos.rs
Labels: network

#412 CI: fix cargo clippy deprecated warnings
  nodes/nomos-node/src/bridges/waku.rs
  nomos-services/consensus/src/network/adapters/mock.rs
  nomos-services/consensus/src/network/adapters/waku.rs
  nomos-services/network/src/backends/mock.rs
Labels: ci

#411 CI: integrations tests libp2p
  ci/Dockerfile
  ci/Jenkinsfile.nightly.integration
Labels: ci

#404 Add da service to nomos node
  nodes/nomos-node/Cargo.toml
  nodes/nomos-node/src/blob.rs
  nodes/nomos-node/src/config.rs
  nodes/nomos-node/src/lib.rs
  nodes/nomos-node/src/main.rs
  nomos-core/src/da/mod.rs
  nomos-da/full-replication/src/lib.rs
  nomos-services/data-availability/src/backend/memory_cache.rs
  nomos-services/data-availability/src/backend/mod.rs
  nomos-services/data-availability/src/lib.rs
  nomos-services/data-availability/src/network/mod.rs
  tests/Cargo.toml
  tests/src/nodes/nomos.rs
Labels: da

#386 Add mixnet retry mechanism
  mixnet/client/Cargo.toml
  mixnet/client/src/config.rs
  mixnet/client/src/lib.rs
  mixnet/client/src/receiver.rs
  mixnet/client/src/sender.rs
  mixnet/node/src/config.rs
  mixnet/node/src/lib.rs
  mixnet/protocol/Cargo.toml
  mixnet/protocol/src/lib.rs
  tests/src/benches/mixnet.rs
  tests/src/nodes/mixnode.rs
  tests/src/nodes/nomos.rs
  tests/src/tests/mixnet.rs
Labels: mixnet

#400 [nomos-cli] Add command to disseminate data
  Cargo.toml
  nomos-cli/Cargo.toml
  nomos-cli/config.yaml
  nomos-cli/src/cmds/disseminate/mod.rs
  nomos-cli/src/cmds/mod.rs
  nomos-cli/src/main.rs
Labels: testnet, da

#418 GH: Run integration tests in all actions
  .github/workflows/codecov.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: ci

#419 Use build all before integration tests
  ci/Jenkinsfile.nightly.integration
Labels: ci

#422 Pipe propose block
  nodes/nomos-node/src/lib.rs
  nomos-core/src/block/builder.rs
  nomos-core/src/da/blob/mod.rs
  nomos-core/src/da/blob/select.rs
  nomos-core/src/da/mod.rs
  nomos-core/src/tx/mod.rs
  nomos-core/src/tx/select.rs
  nomos-services/consensus/src/lib.rs
  tests/src/nodes/nomos.rs
Labels: Block

#429 Remove waku support in nomos-node binary
  nodes/nomos-node/Cargo.toml
  nodes/nomos-node/src/bridges/libp2p.rs
  nodes/nomos-node/src/bridges/mod.rs
  nodes/nomos-node/src/bridges/waku.rs
  nodes/nomos-node/src/config.rs
  nodes/nomos-node/src/lib.rs
  nodes/nomos-node/src/main.rs
  tests/Cargo.toml
  tests/src/nodes/nomos.rs
Labels: refactor, node, waku

#424 Refactor blob -> Blob certificate in Block
  nomos-core/src/block/mod.rs
Labels: refactor, Block

#425 test: Spawn the next leader first
  tests/src/nodes/nomos.rs
Labels: testing

#432 GH: Waku windows build configuration
  .github/actions/mingw-env/action.yml
  .github/workflows/pr.yml
Labels: ci

#434 GH: Use single workflow for master and pr checks
  .github/workflows/build-test.yml
  .github/workflows/pr.yml
Labels: ci

#405 Add concrete Error implementation for mixnet
  mixnet/client/src/error.rs
  mixnet/client/src/lib.rs
  mixnet/client/src/receiver.rs
  mixnet/client/src/sender.rs
  mixnet/node/Cargo.toml
  mixnet/node/src/client_notifier.rs
  mixnet/node/src/lib.rs
  mixnet/protocol/Cargo.toml
  mixnet/protocol/src/lib.rs
  mixnet/topology/Cargo.toml
  mixnet/topology/src/lib.rs
  mixnet/util/Cargo.toml
  mixnet/util/src/lib.rs
Labels: enhancement, mixnet

#416 Add tests for blob dissemination
  nomos-cli/src/cmds/disseminate/mod.rs
  nomos-cli/src/cmds/mod.rs
  nomos-cli/src/lib.rs
  nomos-cli/src/main.rs
  tests/Cargo.toml
  tests/src/nodes/nomos.rs
  tests/src/tests/cli.rs
Labels: testnet, da

#427 Use selection for blob certificates
  nodes/nomos-node/src/lib.rs
  nomos-core/src/block/builder.rs
  nomos-core/src/da/blob/mod.rs
  nomos-core/src/da/certificate/mod.rs
  nomos-core/src/da/certificate/select.rs
  nomos-da/full-replication/src/lib.rs
  nomos-services/consensus/src/lib.rs
Labels: refactor, Block

#435 Mixnet message handle
  .DS_Store
  mixnet/node/Cargo.toml
  mixnet/node/src/config.rs
  mixnet/node/src/lib.rs
  mixnet/protocol/Cargo.toml
  mixnet/protocol/src/lib.rs
  mixnet/util/Cargo.toml
  mixnet/util/src/lib.rs
  tests/src/nodes/mixnode.rs
Labels: mixnet

#430 Report unhappy blocks in happy path test
  tests/Cargo.toml
  tests/src/tests/happy.rs
Labels: enhancement

#438 Fix unhappy test: Handle the case where TARGET_VIEW is reached by timeout_qc
  tests/src/tests/unhappy.rs
Labels: testing

#441 Add discriminant type to allow multiple mempool services
  nodes/nomos-node/src/bridges/mod.rs
  nodes/nomos-node/src/lib.rs
  nomos-services/consensus/src/lib.rs
  nomos-services/mempool/src/lib.rs
  nomos-services/mempool/tests/mock.rs
Labels: bug

#439 Add `send` method to mempool network adapter
  nodes/nomos-node/src/bridges/libp2p.rs
  nodes/nomos-node/src/bridges/mod.rs
  nomos-services/mempool/Cargo.toml
  nomos-services/mempool/src/lib.rs
  nomos-services/mempool/src/network/adapters/libp2p.rs
  nomos-services/mempool/src/network/adapters/mock.rs
  nomos-services/mempool/src/network/adapters/waku.rs
  nomos-services/mempool/src/network/mod.rs
Labels: Mempool, network
