Repository logos-co/nomos, pull requests merged in 2023-11, with the labels that each got.

#487 Da blob api
  nodes/nomos-node-api/src/http/backend/axum.rs
  nodes/nomos-node-api/src/http/da.rs
  nomos-da/full-replication/src/lib.rs
Labels: enhancement

#489 Mempool add APIs
  nodes/nomos-node-api/src/http/backend/axum.rs
  nodes/nomos-node-api/src/http/mempool.rs
  nodes/nomos-node-api/src/http/mod.rs
Labels: enhancement

#476 Nomos http API
  consensus-engine/Cargo.toml
  consensus-engine/src/types.rs
  consensus-engine/src/types/committee.rs
  consensus-engine/src/types/node_id.rs
  consensus-engine/src/types/view.rs
  nodes/nomos-node-api/Cargo.toml
  nodes/nomos-node-api/src/http/backend/axum.rs
  nodes/nomos-node-api/src/http/consensus.rs
  nodes/nomos-node-api/src/http/da.rs
  nodes/nomos-node-api/src/http/libp2p.rs
  nodes/nomos-node-api/src/http/mempool.rs
  nodes/nomos-node-api/src/http/mod.rs
  nodes/nomos-node-api/src/http/storage.rs
  nomos-da/full-replication/src/lib.rs
  nomos-services/consensus/Cargo.toml
  nomos-services/consensus/src/lib.rs
  nomos-services/network/Cargo.toml
  nomos-services/network/src/backends/libp2p/command.rs
Labels: enhancement

#498 Set voter to DA attestation
  nodes/nomos-node/config.yaml
  nomos-cli/Cargo.toml
  nomos-cli/src/da/disseminate.rs
  nomos-da/full-replication/src/lib.rs
  tests/src/nodes/nomos.rs
  tests/src/tests/cli.rs
Labels: da

#499 Docker compose static testnet configuration
  compose.static.yml
  testnet/bootstrap_config.yaml
  testnet/libp2p_config.yaml
Labels: testnet

#505 Do not skip Block::id during ser/de
  consensus-engine/src/types.rs
  nomos-core/src/block/mod.rs
  nomos-services/consensus/src/lib.rs
Labels: bug

#504 Fix occasional port conflict in CLI integration test
  tests/src/tests/cli.rs
Labels: testing

#502 Split long consensus response in separate APIs
  consensus-engine/src/lib.rs
  nodes/nomos-node/src/bridges/mod.rs
  nodes/nomos-node/src/main.rs
  nomos-services/consensus/src/lib.rs
  tests/src/nodes/nomos.rs
  tests/src/tests/happy.rs
  tests/src/tests/unhappy.rs
Labels: consensus, testnet

#509 Add `block_info` api for new HTTP service
  nodes/nomos-node-api/src/http/backend/axum.rs
  nodes/nomos-node-api/src/http/consensus.rs
Labels: enhancement

#508 Store logs from failed CI as artifacts
  .github/workflows/build-test.yml
  .github/workflows/codecov.yml
  .gitignore
  tests/src/nodes/nomos.rs
Labels: testing

#515 Limit GetBlocks response size
  nomos-services/consensus/src/lib.rs
Labels: bug, consensus, testnet

#513 Da voter config for docker compose
  compose.static.yml
  nodes/nomos-node/src/config.rs
  nodes/nomos-node/src/lib.rs
  nodes/nomos-node/src/main.rs
  testnet/bootstrap_config.yaml
  testnet/libp2p_config.yaml
  testnet/scripts/run_bootstrap_node.sh
  testnet/scripts/run_nomos_node.sh
Labels: testnet

#518 Add option to provide custom writer to the logger backend
  nomos-services/log/src/lib.rs
Labels: enhancement, test, testnet

#516 Do not exit the process during dissemination
  nomos-cli/src/cmds/disseminate/mod.rs
  nomos-cli/src/da/disseminate.rs
Labels: bug

#490 New http api to nomos-node integration
  nodes/mixnode/Cargo.toml
  nodes/nomos-node-api/Cargo.toml
  nodes/nomos-node-api/src/http/backend/axum.rs
  nodes/nomos-node-api/src/http/consensus.rs
  nodes/nomos-node-api/src/http/mempool.rs
  nodes/nomos-node-api/src/lib.rs
  nodes/nomos-node-api/tests/todo.rs
  nodes/nomos-node/Cargo.toml
  nodes/nomos-node/config.yaml
  nodes/nomos-node/src/bridges/libp2p.rs
  nodes/nomos-node/src/bridges/mod.rs
  nodes/nomos-node/src/config.rs
  nodes/nomos-node/src/lib.rs
  nodes/nomos-node/src/main.rs
  nomos-cli/src/api/da.rs
  nomos-cli/src/api/mempool.rs
  nomos-da/full-replication/src/lib.rs
  tests/Cargo.toml
  tests/src/nodes/nomos.rs
  tests/src/tests/cli.rs
Labels: enhancement

#517 Add option to not collect logs
  nomos-services/log/src/lib.rs
Labels: enhancement

#520 Update env and config files for testnet
  .env.testnet
  testnet/bootstrap_config.yaml
  testnet/libp2p_config.yaml
  testnet/scripts/run_bootstrap_node.sh
  testnet/scripts/run_nomos_node.sh
Labels: testnet

#521 Rerefactor nomos api
  Cargo.toml
  nodes/nomos-node-api/src/http/backend/mod.rs
  nodes/nomos-node/Cargo.toml
  nodes/nomos-node/src/api.rs
  nodes/nomos-node/src/config.rs
  nodes/nomos-node/src/lib.rs
  nomos-services/api/Cargo.toml
  nomos-services/api/src/http/cl.rs
  nomos-services/api/src/http/consensus.rs
  nomos-services/api/src/http/da.rs
  nomos-services/api/src/http/libp2p.rs
  nomos-services/api/src/http/mempool.rs
  nomos-services/api/src/http/mod.rs
  nomos-services/api/src/http/storage.rs
  nomos-services/api/src/lib.rs
  nomos-services/api/tests/todo.rs
  tests/Cargo.toml
  tests/src/nodes/nomos.rs
Labels: refactor

#524 Update testnet related configuration
  .env.testnet
  testnet/bootstrap_config.yaml
  testnet/libp2p_config.yaml
  testnet/mixnode_config.yaml
Labels: testnet

#525 Fix nomos-cli api
  nomos-cli/src/api/da.rs
  nomos-cli/src/api/mempool.rs
  nomos-cli/src/api/storage.rs
Labels: bug

#534 Update Jenkins CI to rust 1.73.0
  ci/Dockerfile
  shell.nix
Labels: ci

#535 Update rust to 1.74.0 in testnet and CI
  Dockerfile
  ci/Dockerfile
  shell.nix
  testnet/Dockerfile
Labels: ci, testnet

#538 Update code according to the latest `rust-kzg`
  nomos-da/kzg/Cargo.toml
  nomos-da/kzg/src/dynamic_kzg.rs
Labels: da

#501 Reestablish conn with mixnode if err occurs
  nomos-services/network/src/backends/libp2p/mixnet.rs
Labels: mixnet
