Repository logos-co/nomos, pull requests merged in 2024-07, with the labels that each got.

#670 DA Http Endpoints
  nodes/nomos-node/Cargo.toml
  nodes/nomos-node/src/api.rs
  nodes/nomos-node/src/config.rs
  nodes/nomos-node/src/lib.rs
  nodes/nomos-node/src/main.rs
  nomos-da/kzgrs-backend/Cargo.toml
  nomos-da/kzgrs-backend/src/common/blob.rs
  nomos-da/kzgrs-backend/src/common/mod.rs
  nomos-da/kzgrs-backend/src/dispersal.rs
  nomos-services/api/Cargo.toml
  nomos-services/api/src/http/consensus/cryptarchia.rs
  nomos-services/api/src/http/da.rs
  nomos-services/api/src/http/mod.rs
  nomos-services/mempool/Cargo.toml
  nomos-services/mempool/src/da/verify/kzgrs.rs
  nomos-services/mempool/src/da/verify/mod.rs
  tests/Cargo.toml
  tests/src/nodes/nomos.rs
Labels: da

#671 Da: Encoder bench crosscheck sizes
  nomos-da/kzgrs-backend/benches/encoder.rs
Labels: da

#673 Core services tracing spans
  nodes/nomos-node/Cargo.toml
  nodes/nomos-node/src/main.rs
  nomos-libp2p/Cargo.toml
  nomos-services/cryptarchia-consensus/Cargo.toml
  nomos-services/cryptarchia-consensus/src/lib.rs
  nomos-services/data-availability/verifier/src/lib.rs
Labels: Log

#672 Da: verifier bench
  nomos-da/kzgrs-backend/Cargo.toml
  nomos-da/kzgrs-backend/benches/verifier.rs
  nomos-da/kzgrs-backend/src/dispersal.rs
  nomos-da/kzgrs-backend/src/verifier.rs
  nomos-services/data-availability/verifier/src/backend/kzgrs.rs
Labels: da

#678 DA Prost integration
  .github/workflows/build-test.yml
  .github/workflows/codecov.yml
  Cargo.toml
  nomos-da/network/dispersal/Cargo.toml
  nomos-da/network/dispersal/build.rs
  nomos-da/network/dispersal/proto/dispersal.proto
  nomos-da/network/dispersal/src/lib.rs
  nomos-da/network/dispersal/src/proto/dispersal.rs
  nomos-da/network/dispersal/src/proto/mod.rs
Labels: da

#679 DA Improve indexer integration test
  .github/workflows/build-test.yml
  .github/workflows/codecov.yml
  nomos-libp2p/Cargo.toml
  nomos-services/data-availability/tests/Cargo.toml
  nomos-services/data-availability/tests/src/indexer_integration.rs
Labels: test, da

#682 CI: Protoc in testnet and integration tests
  Dockerfile
  ci/Dockerfile
  shell.nix
  testnet/Dockerfile
Labels: ci

#681 DA: Network message types
  Cargo.toml
  nomos-da/network/dispersal/build.rs
  nomos-da/network/dispersal/proto/dispersal.proto
  nomos-da/network/dispersal/src/lib.rs
  nomos-da/network/dispersal/src/proto/dispersal.rs
  nomos-da/network/messages/Cargo.toml
  nomos-da/network/messages/build.rs
  nomos-da/network/messages/proto/common.proto
  nomos-da/network/messages/proto/dispersal.proto
  nomos-da/network/messages/proto/replication.proto
  nomos-da/network/messages/proto/sampling.proto
  nomos-da/network/messages/src/dispersal.rs
  nomos-da/network/messages/src/lib.rs
  nomos-da/network/messages/src/replication.rs
  nomos-da/network/messages/src/sampling.rs
Labels: network, da

#680 Da: network core
  Cargo.toml
  nomos-da/network/core/Cargo.toml
  nomos-da/network/core/src/dispersal/mod.rs
  nomos-da/network/core/src/lib.rs
  nomos-da/network/core/src/protocol.rs
  nomos-da/network/core/src/replication/behaviour.rs
  nomos-da/network/core/src/replication/handler.rs
  nomos-da/network/core/src/replication/mod.rs
  nomos-da/network/core/src/sampling/mod.rs
  nomos-da/network/messages/proto/dispersal.proto
  nomos-da/network/messages/proto/replication.proto
  nomos-da/network/messages/src/dispersal.rs
  nomos-da/network/messages/src/lib.rs
  nomos-da/network/subnetworks-assignations/Cargo.toml
  nomos-da/network/subnetworks-assignations/src/lib.rs
Labels: network, da

#683 Create basic structure of mempool network adapter for da sampling
  nomos-da/network/core/Cargo.toml
  nomos-da/network/core/src/lib.rs
  nomos-da/network/core/src/replication/behaviour.rs
  nomos-services/mempool/Cargo.toml
  nomos-services/mempool/src/da/mod.rs
  nomos-services/mempool/src/da/network/adapters/libp2p.rs
  nomos-services/mempool/src/da/network/adapters/mod.rs
  nomos-services/mempool/src/da/network/mod.rs
Labels: network, da

#684 CI: Rust 1.80
  Dockerfile
  ci/Dockerfile
  nomos-core/src/header/cryptarchia.rs
  shell.nix
  testnet/Dockerfile
Labels: ci
