Repository logos-co/nomos, pull requests merged in 2024-12, with the labels that each got.

#932 Add reconstruct bench
  nomos-da/kzgrs-backend/Cargo.toml
  nomos-da/kzgrs-backend/benches/reconstruct.rs
Labels: bench, da, blob

#928 Mix: Add connection maintenance
  nodes/nomos-node/src/config.rs
  nomos-mix/core/Cargo.toml
  nomos-mix/core/src/conn_maintenance.rs
  nomos-mix/core/src/lib.rs
  nomos-mix/core/src/membership.rs
  nomos-mix/network/Cargo.toml
  nomos-mix/network/src/behaviour.rs
  nomos-mix/network/src/handler.rs
  nomos-mix/network/src/lib.rs
  nomos-services/data-availability/tests/src/common.rs
  nomos-services/mix/src/backends/libp2p.rs
  nomos-services/mix/src/backends/mod.rs
  tests/src/topology/configs/mix.rs
Labels: mixnet

#930 Update benchmark parameters for rs-decode.
  nomos-da/kzgrs/benches/rs.rs
Labels: bench

#931 feature(tracing): bandwith on DA
  nomos-da/network/core/src/protocols/dispersal/validator/behaviour.rs
  nomos-da/network/core/src/protocols/replication/behaviour.rs
  nomos-da/network/core/src/swarm/executor.rs
  nomos-da/network/core/src/swarm/validator.rs
Labels: da, metrics

#934 feature(tracing): Bandwidth on Consensus
  nomos-core/chain-defs/src/block/mod.rs
  nomos-core/chain-defs/src/header/mod.rs
  nomos-services/cryptarchia-consensus/src/lib.rs
Labels: consensus, metrics

#942 ci(pre-commit): config and docs
  .pre-commit-config.yaml
  CONTRIBUTING.md
Labels: documentation, ci

#945 feature(da): Rust-based protobuf-like protocol
  nomos-da/kzgrs-backend/benches/verifier.rs
  nomos-da/kzgrs-backend/src/common/blob.rs
  nomos-da/kzgrs-backend/src/common/mod.rs
  nomos-da/kzgrs-backend/src/dispersal.rs
  nomos-da/kzgrs-backend/src/verifier.rs
  nomos-da/network/core/src/lib.rs
  nomos-da/network/core/src/protocols/dispersal/executor/behaviour.rs
  nomos-da/network/core/src/protocols/dispersal/mod.rs
  nomos-da/network/core/src/protocols/dispersal/validator/behaviour.rs
  nomos-da/network/core/src/protocols/replication/behaviour.rs
  nomos-da/network/core/src/protocols/replication/handler.rs
  nomos-da/network/core/src/protocols/replication/mod.rs
  nomos-da/network/core/src/protocols/sampling/behaviour.rs
  nomos-da/network/core/src/swarm/common.rs
  nomos-da/network/core/src/test_utils.rs
  nomos-da/network/messages/Cargo.toml
  nomos-da/network/messages/build.rs
  nomos-da/network/messages/src/common.rs
  nomos-da/network/messages/src/dispersal.rs
  nomos-da/network/messages/src/lib.rs
  nomos-da/network/messages/src/packing.rs
  nomos-da/network/messages/src/replication.rs
  nomos-da/network/messages/src/sampling.rs
  nomos-da/network/subnetworks-assignations/src/versions/v1.rs
  nomos-da/network/subnetworks-assignations/src/versions/v2.rs
  nomos-services/data-availability/dispersal/src/backend/kzgrs.rs
  nomos-services/data-availability/network/src/backends/libp2p/common.rs
  nomos-services/data-availability/network/src/backends/libp2p/executor.rs
  nomos-services/data-availability/verifier/src/backend/kzgrs.rs
  tests/src/topology/configs/da.rs
Labels: network, da

#946 refactor: Replace remaining bincode calls with wire.
  nodes/nomos-node/Cargo.toml
  nomos-core/chain-defs/src/wire.rs
  nomos-da/network/core/Cargo.toml
  nomos-da/network/core/src/protocols/dispersal/executor/behaviour.rs
  nomos-da/network/core/src/protocols/mod.rs
  nomos-da/network/core/src/protocols/sampling/behaviour.rs
  nomos-services/mempool/Cargo.toml
Labels: refactor, network

#957 fix(blend): correctly check the last layer in `MockBlendMessage`
  nomos-blend/message/src/mock/error.rs
  nomos-blend/message/src/mock/mod.rs
Labels: blendnet

#965 chore(dependencies): Update overwatch dependencies to enable instrument gating.
  nodes/nomos-executor/Cargo.toml
  nodes/nomos-node/Cargo.toml
  nomos-services/api/Cargo.toml
  nomos-services/blend/Cargo.toml
  nomos-services/cryptarchia-consensus/Cargo.toml
  nomos-services/data-availability/dispersal/Cargo.toml
  nomos-services/data-availability/indexer/Cargo.toml
  nomos-services/data-availability/network/Cargo.toml
  nomos-services/data-availability/sampling/Cargo.toml
  nomos-services/data-availability/tests/Cargo.toml
  nomos-services/data-availability/verifier/Cargo.toml
  nomos-services/mempool/Cargo.toml
  nomos-services/network/Cargo.toml
  nomos-services/storage/Cargo.toml
  nomos-services/system-sig/Cargo.toml
  nomos-services/tracing/Cargo.toml
  tests/Cargo.toml
Labels: dependencies

#951 refactor(tests): Gather utilities
  nomos-da/kzgrs-backend/Cargo.toml
  nomos-da/kzgrs-backend/src/lib.rs
  nomos-da/kzgrs-backend/src/testutils/blob.rs
  nomos-da/kzgrs-backend/src/testutils/encoder.rs
  nomos-da/kzgrs-backend/src/testutils/mod.rs
  nomos-da/network/core/Cargo.toml
  nomos-da/network/core/src/protocols/replication/behaviour.rs
  nomos-da/network/core/src/protocols/replication/mod.rs
  nomos-da/network/messages/Cargo.toml
  nomos-da/network/messages/src/packing.rs
Labels: testing

#952 feature(encoder): Implement Iterator over DaBlob for EncodedData
  nomos-da/kzgrs-backend/src/encoder.rs
Labels: da

#950 feature(wire): Wrap errors
  nomos-core/chain-defs/src/wire.rs
  nomos-core/chain-defs/src/wire/bincode.rs
  nomos-core/chain-defs/src/wire/deserialization.rs
  nomos-core/chain-defs/src/wire/errors.rs
  nomos-core/chain-defs/src/wire/mod.rs
  nomos-core/chain-defs/src/wire/serialization.rs
  nomos-da/network/core/Cargo.toml
  nomos-da/network/core/src/protocols/dispersal/executor/behaviour.rs
  nomos-da/network/core/src/protocols/mod.rs
  nomos-da/network/core/src/protocols/replication/mod.rs
  nomos-da/network/core/src/protocols/sampling/behaviour.rs
  nomos-da/network/messages/src/packing.rs
Labels: network

#966 chore(encoder): Replace ad-hoc DaBlob iterations
  nomos-services/data-availability/dispersal/src/backend/kzgrs.rs
Labels: refactor

#967 test(blend): add `MockBlendMessage::payload` function
  nomos-blend/message/src/mock/mod.rs
Labels: blendnet

#968 feature(tracing): Trace blob by id in network
  compose.debug.yml
  compose.static.yml
  nodes/nomos-executor/src/main.rs
  nodes/nomos-node/src/main.rs
  nomos-services/data-availability/dispersal/Cargo.toml
  nomos-services/data-availability/dispersal/src/backend/mod.rs
  nomos-services/data-availability/dispersal/src/lib.rs
  nomos-services/data-availability/indexer/Cargo.toml
  nomos-services/data-availability/indexer/src/lib.rs
  nomos-services/data-availability/network/Cargo.toml
  nomos-services/data-availability/network/src/backends/libp2p/executor.rs
  nomos-services/data-availability/network/src/backends/libp2p/validator.rs
  nomos-services/data-availability/network/src/lib.rs
  nomos-services/data-availability/sampling/Cargo.toml
  nomos-services/data-availability/sampling/src/backend/kzgrs.rs
  nomos-services/data-availability/sampling/src/lib.rs
  nomos-services/data-availability/verifier/Cargo.toml
  nomos-services/data-availability/verifier/src/lib.rs
  nomos-tracing/Cargo.toml
  nomos-tracing/src/tracing/macros.rs
  nomos-tracing/src/tracing/mod.rs
  nomos-tracing/src/tracing/otlp.rs
  testnet/cfgsync/src/config.rs
  testnet/monitoring/grafana/datasources.yaml
  testnet/monitoring/tempo.yaml
  tests/src/tests/da.rs
  tests/src/topology/configs/tracing.rs
Labels: metrics

#974 chore(ci): Github action to publish testnet docker images
  .github/workflows/publish-testnet-image.yml
  compose.static.yml
Labels: testnet

#976 fix(testnet): Unsupported risc0 platform
  .github/workflows/publish-testnet-image.yml
Labels: testnet

#973 feature(kzgrs): Use only commitment hash on encoder and verifier.
  nomos-da/kzgrs-backend/src/common/mod.rs
  nomos-da/kzgrs-backend/src/encoder.rs
  nomos-da/kzgrs-backend/src/verifier.rs
Labels: kzg, da
