Repository logos-co/nomos, pull requests merged in 2024-01, with the labels that each got.

#547 Unbox select traits
  nomos-core/src/da/certificate/mod.rs
  nomos-core/src/da/certificate/select.rs
  nomos-core/src/tx/mod.rs
  nomos-core/src/tx/select.rs
  nomos-core/src/utils/select.rs
Labels: refactor

#548 Set and get blocks tip without filtering
  consensus-engine/src/lib.rs
Labels: consensus

#550 Bump to rust 1.75
  Dockerfile
  ci/Dockerfile
  shell.nix
  testnet/Dockerfile
Labels: ci

#545 Tests for tree overlay level sizes
  consensus-engine/src/overlay/tree_overlay/tree.rs
Labels: consensus, test

#495 Add chat demo for testnet
  nomos-cli/Cargo.toml
  nomos-cli/src/api/consensus.rs
  nomos-cli/src/cmds/chat/mod.rs
  nomos-cli/src/cmds/chat/ui.rs
  nomos-cli/src/cmds/disseminate/mod.rs
  nomos-cli/src/cmds/mod.rs
  nomos-cli/src/da/disseminate.rs
  nomos-services/log/src/lib.rs
Labels: testnet, da

#553 Testnet config update for nomos.tech
  compose.static.yml
  testnet/bootstrap_config.yaml
  testnet/libp2p_config.yaml
Labels: testnet

#554 Receive blocks blobs in parallel
  nomos-cli/config.yaml
  nomos-cli/src/cmds/chat/mod.rs
Labels: enhancement

#555 Nomos chat fixes
  nomos-cli/Cargo.toml
  nomos-cli/src/cmds/chat/mod.rs
  nomos-cli/src/cmds/chat/ui.rs
Labels: testnet

#556 Rename consensus service to carnot consensus
  Cargo.toml
  nodes/nomos-node/Cargo.toml
  nodes/nomos-node/src/lib.rs
  nomos-cli/Cargo.toml
  nomos-cli/src/api/consensus.rs
  nomos-services/api/Cargo.toml
  nomos-services/api/src/http/consensus.rs
  nomos-services/carnot-consensus/Cargo.toml
  nomos-services/carnot-consensus/src/committee_membership/mod.rs
  nomos-services/carnot-consensus/src/leader_selection/mod.rs
  nomos-services/carnot-consensus/src/lib.rs
  nomos-services/carnot-consensus/src/network/adapters/libp2p.rs
  nomos-services/carnot-consensus/src/network/adapters/mock.rs
  nomos-services/carnot-consensus/src/network/adapters/mod.rs
  nomos-services/carnot-consensus/src/network/messages.rs
  nomos-services/carnot-consensus/src/network/mod.rs
  nomos-services/carnot-consensus/src/tally/happy.rs
  nomos-services/carnot-consensus/src/tally/mod.rs
  nomos-services/carnot-consensus/src/tally/timeout.rs
  nomos-services/carnot-consensus/src/tally/unhappy.rs
  nomos-services/carnot-consensus/src/task_manager.rs
  nomos-services/carnot-consensus/src/test.rs
  nomos-services/carnot-consensus/src/view_cancel.rs
  simulations/Cargo.toml
  simulations/src/node/carnot/event_builder.rs
  simulations/src/node/carnot/messages.rs
  simulations/src/node/carnot/mod.rs
  tests/Cargo.toml
  tests/src/nodes/nomos.rs
  tests/src/tests/unhappy.rs
Labels: refactor

#522 Prometheus metrics service
  Cargo.toml
  nodes/nomos-node/Cargo.toml
  nodes/nomos-node/src/api.rs
  nodes/nomos-node/src/config.rs
  nodes/nomos-node/src/lib.rs
  nodes/nomos-node/src/main.rs
  nomos-metrics/Cargo.toml
  nomos-metrics/src/lib.rs
  nomos-services/api/Cargo.toml
  nomos-services/api/src/http/metrics.rs
  nomos-services/api/src/http/mod.rs
  nomos-services/mempool/Cargo.toml
  nomos-services/mempool/src/lib.rs
  nomos-services/mempool/src/metrics.rs
  nomos-services/mempool/tests/mock.rs
Labels: metrics

#557 bump rayon version to make cargo work
  simulations/Cargo.toml
Labels: bug

#563 Add test for big blob dissemination
  nomos-cli/src/da/retrieve.rs
  tests/src/nodes/nomos.rs
  tests/src/tests/cli.rs
Labels: test

#564 Docker compose metrics containers
  compose.static.yml
  nodes/nomos-node/config.yaml
  testnet/Dockerfile
  testnet/explorer_config.yaml
  testnet/monitoring/grafana/datasources.yaml
  testnet/monitoring/grafana/grafana.ini
  testnet/monitoring/grafana/plugins.env
  testnet/monitoring/prometheus-config.yml
  testnet/scripts/run_bootstrap_node.sh
  testnet/scripts/run_nomos_node.sh
  tests/src/nodes/nomos.rs
Labels: testnet, metrics

#510 Write mixnode logs to files in integration tests
  tests/src/nodes/mixnode.rs
  tests/src/nodes/mod.rs
  tests/src/nodes/nomos.rs
Labels: testing, mixnet

#567 Nomos chat app non interactive
  nomos-cli/src/cmds/chat/mod.rs
  nomos-cli/src/cmds/disseminate/mod.rs
Labels: testnet

#568 Use chat app as testnet bot
  compose.static.yml
  testnet/Dockerfile
  testnet/scripts/run_nomos_bot.sh
Labels: testnet

#574 Add testnet cli_config and volume
  compose.static.yml
  testnet/Dockerfile
  testnet/cli_config.yaml
  testnet/scripts/run_nomos_bot.sh
Labels: testnet

#570 Mixnet v1: Skeleton
  nomos-services/network/src/backends/mixnet/mod.rs
  nomos-services/network/src/backends/mod.rs
Labels: mixnet

#566 Block explorer 2
  nodes/explorer/Cargo.toml
  nodes/explorer/src/api_backend/mod.rs
  nodes/explorer/src/api_backend/store.rs
  nomos-services/storage/src/backends/sled.rs
  nomos-services/storage/src/lib.rs
Labels: enhancement, engine
