Repository logos-co/nomos, pull requests merged in 2024-06, with the labels that each got.

#659 Graylog service for the Testnet
  .env.testnet
  compose.static.yml
  nodes/nomos-node/src/config.rs
  nomos-services/log/Cargo.toml
  nomos-services/log/src/lib.rs
  testnet/monitoring/graylog.conf
  testnet/scripts/run_bootstrap_node.sh
  testnet/scripts/run_nomos_node.sh
Labels: Log, testnet

#662 Added missing generic param to the mempool metrics
  nomos-services/mempool/src/tx/metrics.rs
Labels: Mempool, metrics

#661 Rust 1.79 stable
  Dockerfile
  ci/Dockerfile
  shell.nix
  testnet/Dockerfile
  tests/src/nodes/nomos.rs
Labels: ci

#664 Da: fk20 encoder
  nomos-da/kzgrs-backend/Cargo.toml
  nomos-da/kzgrs-backend/src/dispersal.rs
  nomos-da/kzgrs-backend/src/encoder.rs
  nomos-da/kzgrs-backend/src/global.rs
  nomos-da/kzgrs-backend/src/verifier.rs
  nomos-da/kzgrs/src/rs.rs
  nomos-services/data-availability/verifier/src/backend/kzgrs.rs
Labels: da

#665 Da: parallel encoder
  nomos-da/kzgrs-backend/Cargo.toml
  nomos-da/kzgrs-backend/benches/encoder.rs
  nomos-da/kzgrs-backend/src/common/mod.rs
  nomos-da/kzgrs-backend/src/encoder.rs
Labels: da

#666 Feature flag to toggle tracing
  nodes/nomos-node/Cargo.toml
  nodes/nomos-node/src/lib.rs
  nodes/nomos-node/src/main.rs
Labels: node

#667 Da: cache toeplitz1
  nomos-da/kzgrs-backend/benches/encoder.rs
  nomos-da/kzgrs-backend/src/encoder.rs
  nomos-da/kzgrs/benches/fk20.rs
  nomos-da/kzgrs/src/fk20.rs
Labels: da
