Repository logos-co/nomos, pull requests merged in 2024-04, with the labels that each got.

#636 Split mempool into tx and da mempool
  nodes/nomos-node/src/api.rs
  nodes/nomos-node/src/lib.rs
  nodes/nomos-node/src/main.rs
  nomos-services/api/src/http/cl.rs
  nomos-services/api/src/http/da.rs
  nomos-services/api/src/http/mempool.rs
  nomos-services/cryptarchia-consensus/src/lib.rs
  nomos-services/mempool/src/da/mod.rs
  nomos-services/mempool/src/da/service.rs
  nomos-services/mempool/src/lib.rs
  nomos-services/mempool/src/network/messages.rs
  nomos-services/mempool/src/tx/metrics.rs
  nomos-services/mempool/src/tx/mod.rs
  nomos-services/mempool/src/tx/service.rs
  nomos-services/mempool/tests/mock.rs
Labels: refactor

#633 Da: v1 encoder
  Cargo.toml
  nomos-da/kzgrs-backend/Cargo.toml
  nomos-da/kzgrs-backend/src/common.rs
  nomos-da/kzgrs-backend/src/encoder.rs
  nomos-da/kzgrs-backend/src/global.rs
  nomos-da/kzgrs-backend/src/lib.rs
  nomos-da/kzgrs/Cargo.toml
  nomos-da/kzgrs/src/common.rs
  nomos-da/kzgrs/src/global_parameters.rs
  nomos-da/kzgrs/src/kzg.rs
  nomos-da/kzgrs/src/lib.rs
  nomos-da/kzgrs/src/rs.rs
Labels: da

#635 Da: v1 verifier
  nomos-da/kzgrs-backend/Cargo.toml
  nomos-da/kzgrs-backend/src/common.rs
  nomos-da/kzgrs-backend/src/encoder.rs
  nomos-da/kzgrs-backend/src/lib.rs
  nomos-da/kzgrs-backend/src/verifier.rs
  nomos-da/kzgrs/src/common.rs
  nomos-da/kzgrs/src/rs.rs
Labels: da

#634 DA API Payload to Item in mempool
  nodes/nomos-node/src/lib.rs
  nodes/nomos-node/src/main.rs
  nomos-cli/src/api/da.rs
  nomos-core/src/da/attestation/mod.rs
  nomos-core/src/da/certificate/metadata.rs
  nomos-core/src/da/certificate/mock.rs
  nomos-core/src/da/certificate/mod.rs
  nomos-core/src/da/certificate/vid.rs
  nomos-core/src/da/certificate_metadata.rs
  nomos-core/src/da/mod.rs
  nomos-core/src/da/vid.rs
  nomos-da/full-replication/src/attestation.rs
  nomos-da/full-replication/src/lib.rs
  nomos-da/kzgrs/src/common.rs
  nomos-services/api/src/http/mempool.rs
  nomos-services/cryptarchia-consensus/src/lib.rs
  nomos-services/data-availability/Cargo.toml
  nomos-services/mempool/Cargo.toml
  nomos-services/mempool/src/backend/mockpool.rs
  nomos-services/mempool/src/backend/mod.rs
  nomos-services/mempool/src/da/service.rs
  nomos-services/mempool/src/lib.rs
  nomos-services/mempool/src/network/adapters/libp2p.rs
  nomos-services/mempool/src/network/adapters/mock.rs
  nomos-services/mempool/src/network/mod.rs
  nomos-services/mempool/src/tx/service.rs
  tests/Cargo.toml
  tests/src/nodes/mod.rs
  tests/src/nodes/nomos.rs
  tests/src/tests/cli.rs
  tests/src/tests/cryptarchia/happy.rs
Labels: Mempool, da

#638 Remove duplicate error log in network service
  nomos-services/network/src/backends/libp2p/swarm.rs
Labels: network

#641 DA API Certificate verification
  nodes/nomos-node/src/lib.rs
  nodes/nomos-node/src/main.rs
  nomos-da/full-replication/src/lib.rs
  nomos-services/api/src/http/consensus/cryptarchia.rs
  nomos-services/api/src/http/mempool.rs
  nomos-services/cryptarchia-consensus/src/lib.rs
  nomos-services/mempool/Cargo.toml
  nomos-services/mempool/src/da/mod.rs
  nomos-services/mempool/src/da/service.rs
  nomos-services/mempool/src/da/verify/fullreplication.rs
  nomos-services/mempool/src/da/verify/mod.rs
  nomos-services/mempool/src/lib.rs
  nomos-services/mempool/src/verify/mod.rs
Labels: Mempool, da

#643 DA API Indexer service
  Cargo.toml
  nodes/nomos-node/Cargo.toml
  nodes/nomos-node/src/api.rs
  nomos-cli/Cargo.toml
  nomos-cli/src/api/da.rs
  nomos-core/src/da/certificate/metadata.rs
  nomos-da/full-replication/src/lib.rs
  nomos-services/api/Cargo.toml
  nomos-services/data-availability/Cargo.toml
  nomos-services/data-availability/indexer/Cargo.toml
  nomos-services/data-availability/indexer/src/consensus/adapters/cryptarchia.rs
  nomos-services/data-availability/indexer/src/consensus/adapters/mod.rs
  nomos-services/data-availability/indexer/src/consensus/mod.rs
  nomos-services/data-availability/indexer/src/indexer/mod.rs
  nomos-services/data-availability/indexer/src/lib.rs
  nomos-services/data-availability/indexer/src/storage/mod.rs
  nomos-services/data-availability/src/lib.rs
  nomos-services/mempool/Cargo.toml
  tests/Cargo.toml
Labels: da
