Repository logos-co/nomos, pull requests merged in 2024-11, with the labels that each got.

#896 Mix: Use streams in message blend and mix service
  nomos-mix/core/src/lib.rs
  nomos-mix/core/src/message_blend/crypto.rs
  nomos-mix/core/src/message_blend/mod.rs
  nomos-mix/core/src/message_blend/temporal.rs
  nomos-mix/core/src/persistent_transmission.rs
  nomos-services/mix/src/lib.rs
  tests/src/nodes/executor.rs
  tests/src/nodes/validator.rs
Labels: refactor, mixnet

#903 Mix: Abstract persistent transmission rng
  nomos-mix/core/Cargo.toml
  nomos-mix/core/src/persistent_transmission.rs
  nomos-services/mix/Cargo.toml
  nomos-services/mix/src/lib.rs
Labels: refactor, mixnet

#904 Mix: Abstract blend rng
  nomos-mix/core/src/message_blend/mod.rs
  nomos-mix/core/src/message_blend/temporal.rs
  nomos-services/mix/src/lib.rs
Labels: refactor, mixnet

#906 Mix: time abstract from streams
  nomos-mix/core/src/message_blend/mod.rs
  nomos-mix/core/src/message_blend/temporal.rs
  nomos-mix/core/src/persistent_transmission.rs
  nomos-services/data-availability/tests/src/common.rs
  nomos-services/mix/src/lib.rs
  tests/src/nodes/executor.rs
  tests/src/nodes/validator.rs
Labels: refactor, mixnet

#908 Add Sync bound to BoxStream in blend stream
  nomos-mix/core/src/message_blend/mod.rs
Labels: refactor, mixnet

#909 Tracing: Otlp metrics
  Cargo.toml
  README.md
  compose.debug.yml
  compose.static.yml
  nodes/nomos-executor/Cargo.toml
  nodes/nomos-executor/src/api/backend.rs
  nodes/nomos-executor/src/lib.rs
  nodes/nomos-executor/src/main.rs
  nodes/nomos-node/Cargo.toml
  nodes/nomos-node/src/api/backend.rs
  nodes/nomos-node/src/api/handlers.rs
  nodes/nomos-node/src/api/paths.rs
  nodes/nomos-node/src/config.rs
  nodes/nomos-node/src/lib.rs
  nodes/nomos-node/src/main.rs
  nomos-services/api/Cargo.toml
  nomos-services/api/src/http/metrics.rs
  nomos-services/api/src/http/mod.rs
  nomos-services/data-availability/tests/src/common.rs
  nomos-services/mempool/Cargo.toml
  nomos-services/mempool/src/da/service.rs
  nomos-services/mempool/src/tx/metrics.rs
  nomos-services/mempool/src/tx/mod.rs
  nomos-services/mempool/src/tx/service.rs
  nomos-services/mempool/tests/mock.rs
  nomos-services/metrics/Cargo.toml
  nomos-services/metrics/src/lib.rs
  nomos-services/tracing/src/lib.rs
  nomos-tracing/Cargo.toml
  nomos-tracing/src/lib.rs
  nomos-tracing/src/metrics/mod.rs
  nomos-tracing/src/metrics/otlp.rs
  testnet/cfgsync.yaml
  testnet/cfgsync/src/bin/cfgsync-server.rs
  testnet/cfgsync/src/config.rs
  testnet/cfgsync/src/lib.rs
  testnet/monitoring/prometheus.yml
  tests/Cargo.toml
  tests/src/topology/configs/tracing.rs
Labels: Mempool, metrics

#910 Mix: Implemented cover traffic
  nomos-mix/core/Cargo.toml
  nomos-mix/core/src/cover_traffic.rs
  nomos-mix/core/src/lib.rs
Labels: mixnet

#907 RS: Add rs encode/decode benches
  nomos-da/kzgrs/Cargo.toml
  nomos-da/kzgrs/benches/rs.rs
Labels: rs, bench

#911 Add clone and copy to CoverTrafficSettings
  .gitignore
  nomos-mix/core/src/cover_traffic.rs
Labels: bug, mixnet

#913 Add derives CoverTrafficSettings
  nomos-mix/core/src/cover_traffic.rs
Labels: bug, mixnet

#915 Mix: Fix bug in cover traffic ticket generation
  nomos-mix/core/src/cover_traffic.rs
Labels: bug, mixnet

#897 Mix: Packet header encryption
  nomos-mix/core/src/message_blend/crypto.rs
  nomos-mix/core/src/message_blend/mod.rs
  nomos-mix/message/Cargo.toml
  nomos-mix/message/src/lib.rs
  nomos-mix/message/src/mock/error.rs
  nomos-mix/message/src/mock/mod.rs
  nomos-mix/message/src/sphinx/error.rs
  nomos-mix/message/src/sphinx/layered_cipher.rs
  nomos-mix/message/src/sphinx/mod.rs
  nomos-mix/message/src/sphinx/packet.rs
  nomos-mix/message/src/sphinx/routing.rs
Labels: mixnet

#919 Mix: Don't panic on SendError in libp2p mix backend
  nomos-services/mix/src/backends/libp2p.rs
Labels: mixnet

#920 Mix: Integrate cover traffic to mix service
  nodes/nomos-node/config.yaml
  nomos-mix/core/src/cover_traffic.rs
  nomos-mix/core/src/membership.rs
  nomos-services/data-availability/tests/src/common.rs
  nomos-services/mix/src/lib.rs
  tests/src/nodes/executor.rs
  tests/src/nodes/validator.rs
Labels: mixnet

#923 Mix: Re-define max_payload_size parameter
  nomos-mix/message/src/mock/mod.rs
  nomos-mix/message/src/sphinx/mod.rs
  nomos-mix/message/src/sphinx/packet.rs
Labels: mixnet

#924 Mix: Use Sphinx instead of mock
  nomos-mix/message/src/sphinx/mod.rs
  nomos-services/data-availability/tests/src/common.rs
  nomos-services/mix/Cargo.toml
  nomos-services/mix/src/backends/libp2p.rs
  nomos-services/mix/src/backends/mod.rs
  nomos-services/mix/src/lib.rs
  testnet/cfgsync/src/config.rs
  tests/src/topology/configs/mix.rs
Labels: mixnet
