Repository logos-co/nomos, pull requests merged in 2025-05, with the labels that each got.

#1257 refactor(sdp): Activity message
  nomos-sdp/src/ledger.rs
  nomos-sdp/src/lib.rs
  nomos-sdp/src/state.rs
  nomos-services/sdp/src/adapters/rewards/mod.rs
  nomos-services/sdp/src/adapters/services/mod.rs
  nomos-services/sdp/src/backends/ledger.rs
  nomos-services/sdp/src/lib.rs
Labels: sdp

#1267 (PoC/Storage): New storage abstraction layer
  .cargo-deny.toml
  Cargo.toml
  dependencies_graph.dot
  nomos-core/chain-defs/src/block/mod.rs
  nomos-da/storage/Cargo.toml
  nomos-da/storage/src/lib.rs
  nomos-services/api/Cargo.toml
  nomos-services/api/src/http/da_shares.rs
  nomos-services/api/src/http/storage.rs
  nomos-services/cryptarchia-consensus/Cargo.toml
  nomos-services/cryptarchia-consensus/src/lib.rs
  nomos-services/cryptarchia-consensus/src/relays.rs
  nomos-services/cryptarchia-consensus/src/storage/adapters/storage.rs
  nomos-services/cryptarchia-consensus/src/storage/mod.rs
  nomos-services/data-availability/indexer/Cargo.toml
  nomos-services/data-availability/indexer/src/storage/adapters/rocksdb.rs
  nomos-services/data-availability/sampling/Cargo.toml
  nomos-services/data-availability/sampling/src/storage/adapters/rocksdb.rs
  nomos-services/data-availability/verifier/Cargo.toml
  nomos-services/data-availability/verifier/src/storage/adapters/rocksdb.rs
  nomos-services/storage/Cargo.toml
  nomos-services/storage/src/api/backend/mod.rs
  nomos-services/storage/src/api/backend/rocksdb/blocks.rs
  nomos-services/storage/src/api/backend/rocksdb/da.rs
  nomos-services/storage/src/api/backend/rocksdb/mod.rs
  nomos-services/storage/src/api/backend/rocksdb/utils.rs
  nomos-services/storage/src/api/chain/mod.rs
  nomos-services/storage/src/api/chain/requests.rs
  nomos-services/storage/src/api/da/mod.rs
  nomos-services/storage/src/api/da/requests.rs
  nomos-services/storage/src/api/mod.rs
  nomos-services/storage/src/backends/mock.rs
  nomos-services/storage/src/backends/mod.rs
  nomos-services/storage/src/backends/rocksdb.rs
  nomos-services/storage/src/backends/sled.rs
  nomos-services/storage/src/lib.rs
Labels: storage

#1273 Use new storage abstraction layer for storage access
  Cargo.toml
  nodes/nomos-executor/executor/src/api/backend.rs
  nodes/nomos-node/node/Cargo.toml
  nodes/nomos-node/node/src/api/backend.rs
  nodes/nomos-node/node/src/api/handlers.rs
  nomos-core/chain-defs/Cargo.toml
  nomos-da/kzgrs-backend/Cargo.toml
  nomos-da/kzgrs-backend/src/common/share.rs
  nomos-services/api/Cargo.toml
  nomos-services/api/src/http/da_shares.rs
  nomos-services/api/src/http/storage.rs
  nomos-services/data-availability/indexer/Cargo.toml
  nomos-services/data-availability/indexer/src/storage/adapters/rocksdb.rs
  nomos-services/data-availability/sampling/src/storage/adapters/rocksdb.rs
  nomos-services/data-availability/verifier/src/storage/adapters/rocksdb.rs
  nomos-services/key-management-system/Cargo.toml
  nomos-services/storage/Cargo.toml
  nomos-services/storage/src/api/backend/rocksdb/da.rs
  nomos-services/storage/src/api/da/mod.rs
  nomos-services/storage/src/api/da/requests.rs
  nomos-services/storage/src/backends/mock.rs
Labels: storage

#1259 feat(da): DA v1.1
  nomos-da/kzgrs-backend/benches/encoder.rs
  nomos-da/kzgrs-backend/benches/verifier.rs
  nomos-da/kzgrs-backend/src/common/mod.rs
  nomos-da/kzgrs-backend/src/common/share.rs
  nomos-da/kzgrs-backend/src/dispersal.rs
  nomos-da/kzgrs-backend/src/encoder.rs
  nomos-da/kzgrs-backend/src/reconstruction.rs
  nomos-da/kzgrs-backend/src/testutils/blob.rs
  nomos-da/kzgrs-backend/src/verifier.rs
  nomos-da/kzgrs/Cargo.toml
  nomos-da/kzgrs/src/bdfg_proving.rs
  nomos-da/kzgrs/src/lib.rs
  nomos-da/network/core/src/protocols/dispersal/mod.rs
  nomos-da/network/core/src/protocols/replication/mod.rs
  nomos-da/network/core/src/protocols/sampling/mod.rs
  nomos-da/network/messages/src/sampling.rs
  nomos-services/cryptarchia-consensus/src/lib.rs
  nomos-services/data-availability/dispersal/src/backend/kzgrs.rs
  nomos-services/data-availability/network/src/backends/mock/executor.rs
  nomos-services/data-availability/sampling/src/backend/kzgrs.rs
  nomos-services/data-availability/sampling/src/lib.rs
  nomos-services/data-availability/verifier/src/backend/kzgrs.rs
  tests/kzgrs/kzgrs_test_params
Labels: da

#1276 Remove da full-replication crate
  Cargo.toml
  dependencies_graph.dot
  nomos-da/full-replication/Cargo.toml
  nomos-da/full-replication/src/lib.rs
Labels: da

#1280 refactor(sdp): Activity contract and proof verification removal
  nomos-sdp/src/ledger.rs
  nomos-sdp/src/lib.rs
  nomos-sdp/src/state.rs
  nomos-services/membership/src/adapters/sdp.rs
  nomos-services/membership/src/backends/mock.rs
  nomos-services/sdp/src/adapters/activity/contract.rs
  nomos-services/sdp/src/adapters/activity/mod.rs
  nomos-services/sdp/src/adapters/mod.rs
  nomos-services/sdp/src/adapters/services/mod.rs
  nomos-services/sdp/src/adapters/services/services_repository.rs
  nomos-services/sdp/src/adapters/stakes/mod.rs
  nomos-services/sdp/src/adapters/stakes/verifier.rs
  nomos-services/sdp/src/backends/ledger.rs
  nomos-services/sdp/src/backends/mod.rs
  nomos-services/sdp/src/lib.rs
Labels: sdp

#1282 ci: Use linux label for self-hosted runner
  .github/workflows/code-check.yml
Labels: ci

#1281 feature(http): Http storage adapter
  nodes/nomos-executor/executor/src/api/backend.rs
  nodes/nomos-executor/executor/src/lib.rs
  nodes/nomos-node/node/src/api/backend.rs
  nodes/nomos-node/node/src/api/handlers.rs
  nodes/nomos-node/node/src/lib.rs
  nomos-services/api/src/http/da_shares.rs
  nomos-services/api/src/http/mod.rs
  nomos-services/api/src/http/storage.rs
  nomos-services/api/src/http/storage/adapters/mod.rs
  nomos-services/api/src/http/storage/adapters/rocksdb.rs
  nomos-services/api/src/http/storage/mod.rs
Labels: http

#1299 chore(ci): Update macos image to self-hosted
  .github/workflows/code-check.yml
Labels: chore

#1302 chore(ci): Update cargo version
  .github/workflows/code-check.yml
Labels: versioning, ci

#1294 chore(pre-commit): Add cargo machete to pre-commit hooks.
  .pre-commit-config.yaml
Labels: chore
