Repository logos-co/nomos, pull requests merged in 2025-03, with the labels that each got.

#1082 fix: Cfgsync tests for DA addressbook update
  testnet/cfgsync/Cargo.toml
  testnet/cfgsync/src/bin/cfgsync-client.rs
  testnet/cfgsync/src/bin/cfgsync-server.rs
  testnet/cfgsync/src/client.rs
  testnet/cfgsync/src/config.rs
  testnet/cfgsync/src/lib.rs
  testnet/cfgsync/src/repo.rs
  testnet/cfgsync/src/server.rs
  tests/src/topology/configs/da.rs
Labels: testnet

#1083 feat(DA): Balancer handles subnetwork connections in executor and validator swarms
  nomos-da/network/core/src/behaviour/executor.rs
  nomos-da/network/core/src/maintenance/balancer.rs
  nomos-da/network/core/src/protocols/dispersal/executor/behaviour.rs
  nomos-da/network/core/src/protocols/dispersal/mod.rs
  nomos-da/network/core/src/protocols/dispersal/validator/behaviour.rs
  nomos-da/network/core/src/protocols/sampling/behaviour.rs
  nomos-da/network/core/src/swarm/common/balancer.rs
  nomos-da/network/core/src/swarm/common/monitor.rs
  nomos-da/network/core/src/swarm/executor.rs
  nomos-da/network/core/src/swarm/validator.rs
  nomos-da/network/core/src/test_utils.rs
  nomos-da/network/subnetworks-assignations/src/versions/v1.rs
  nomos-da/network/subnetworks-assignations/src/versions/v2.rs
  nomos-services/data-availability/network/src/backends/libp2p/common.rs
  nomos-services/data-availability/network/src/backends/libp2p/executor.rs
  nomos-services/data-availability/network/src/backends/libp2p/validator.rs
  nomos-services/data-availability/tests/Cargo.toml
  nomos-services/data-availability/tests/src/common.rs
  testnet/cfgsync.yaml
  testnet/cfgsync/src/config.rs
  testnet/cfgsync/src/lib.rs
  testnet/cfgsync/src/server.rs
  tests/src/nodes/validator.rs
  tests/src/tests/da.rs
  tests/src/topology/configs/da.rs
  tests/src/topology/mod.rs
Labels: network, da

#1081 chore(DA): Remove indexer tests
  .cargo-deny.toml
  Cargo.toml
  nomos-services/data-availability/tests/Cargo.toml
  nomos-services/data-availability/tests/src/common.rs
  nomos-services/data-availability/tests/src/indexer_integration.rs
  nomos-services/data-availability/tests/src/lib.rs
  nomos-services/data-availability/tests/src/rng.rs
  nomos-services/data-availability/tests/src/verifier_integration.rs
Labels: refactor, da

#1109 chore: Use libp2p 0.55 as a workspace dependency
  Cargo.toml
  nomos-blend/network/Cargo.toml
  nomos-da/network/core/Cargo.toml
  nomos-libp2p/Cargo.toml
  nomos-services/blend/Cargo.toml
  nomos-services/data-availability/network/Cargo.toml
  nomos-services/data-availability/verifier/Cargo.toml
Labels: network

#1120 fix: verifier bench wrong sizes reporting
  nomos-da/kzgrs-backend/benches/verifier.rs
Labels: bug, bench

#1108 feat(DA): Sampling requests commitments and blobs separately
  .cargo-deny.toml
  clients/common-http-client/Cargo.toml
  clients/common-http-client/src/lib.rs
  clients/executor-http-client/src/lib.rs
  nodes/nomos-executor/src/api/backend.rs
  nodes/nomos-executor/src/lib.rs
  nodes/nomos-node/Cargo.toml
  nodes/nomos-node/config.yaml
  nodes/nomos-node/src/api/backend.rs
  nodes/nomos-node/src/api/handlers.rs
  nodes/nomos-node/src/api/paths.rs
  nodes/nomos-node/src/lib.rs
  nomos-cli/Cargo.toml
  nomos-cli/src/cmds/executor.rs
  nomos-cli/src/cmds/validator.rs
  nomos-core/chain-defs/src/da/mod.rs
  nomos-da/kzgrs-backend/benches/verifier.rs
  nomos-da/kzgrs-backend/src/common/blob.rs
  nomos-da/kzgrs-backend/src/dispersal.rs
  nomos-da/kzgrs-backend/src/verifier.rs
  nomos-da/network/core/src/protocols/sampling/behaviour.rs
  nomos-da/network/core/src/protocols/sampling/mod.rs
  nomos-da/network/messages/src/common.rs
  nomos-da/network/messages/src/http/da.rs
  nomos-da/network/messages/src/http/mod.rs
  nomos-da/network/messages/src/lib.rs
  nomos-da/network/messages/src/sampling.rs
  nomos-services/api/src/http/consensus/cryptarchia.rs
  nomos-services/api/src/http/da.rs
  nomos-services/api/src/http/mempool.rs
  nomos-services/cryptarchia-consensus/src/lib.rs
  nomos-services/cryptarchia-consensus/src/relays.rs
  nomos-services/data-availability/dispersal/src/adapters/mempool/kzgrs.rs
  nomos-services/data-availability/indexer/src/lib.rs
  nomos-services/data-availability/network/src/backends/libp2p/common.rs
  nomos-services/data-availability/sampling/Cargo.toml
  nomos-services/data-availability/sampling/src/api/http.rs
  nomos-services/data-availability/sampling/src/api/mod.rs
  nomos-services/data-availability/sampling/src/backend/kzgrs.rs
  nomos-services/data-availability/sampling/src/backend/mod.rs
  nomos-services/data-availability/sampling/src/lib.rs
  nomos-services/data-availability/sampling/src/storage/adapters/rocksdb.rs
  nomos-services/data-availability/sampling/src/storage/mod.rs
  nomos-services/data-availability/verifier/src/backend/kzgrs.rs
  nomos-services/data-availability/verifier/src/lib.rs
  nomos-services/data-availability/verifier/src/storage/adapters/rocksdb.rs
  nomos-services/data-availability/verifier/src/storage/mod.rs
  nomos-services/mempool/src/da/service.rs
  tests/src/nodes/executor.rs
  tests/src/nodes/validator.rs
  tests/src/tests/da/api.rs
Labels: da, sampling

#1104 fix(DA): Dispersal service expects correct number of verifier responses
  nomos-da/network/core/src/protocols/sampling/behaviour.rs
  nomos-da/network/messages/src/sampling.rs
  nomos-services/data-availability/dispersal/Cargo.toml
  nomos-services/data-availability/dispersal/src/adapters/network/libp2p.rs
  nomos-services/data-availability/dispersal/src/adapters/network/mod.rs
  nomos-services/data-availability/dispersal/src/backend/kzgrs.rs
  nomos-services/data-availability/network/src/backends/libp2p/common.rs
  nomos-services/data-availability/sampling/src/lib.rs
  testnet/cfgsync.yaml
  testnet/cfgsync/Cargo.toml
  testnet/cfgsync/src/config.rs
  testnet/cfgsync/src/lib.rs
  testnet/cfgsync/src/server.rs
  tests/src/nodes/executor.rs
  tests/src/tests/da/disperse.rs
  tests/src/topology/configs/da.rs
Labels: da

#1124 fix(cfgsync): Dispersal mempool push strategy in cfgsync sample yaml
  testnet/cfgsync.yaml
Labels: testnet

#1127 Remove `base_url` from `CommonHttpClient`
  clients/common-http-client/Cargo.toml
  clients/common-http-client/src/lib.rs
  clients/executor-http-client/src/lib.rs
  nomos-cli/src/cmds/executor.rs
  nomos-services/data-availability/sampling/src/api/http.rs
  tests/src/common/da.rs
  tests/src/nodes/executor.rs
  tests/src/nodes/validator.rs
  tests/src/tests/da/api.rs
Labels: client

#1129 fix(DA): Disperse succeeds when data and metadata is the same
  nomos-services/api/src/http/mempool.rs
  nomos-services/data-availability/dispersal/src/adapters/mempool/kzgrs.rs
  nomos-services/data-availability/dispersal/src/adapters/mempool/mod.rs
  nomos-services/data-availability/dispersal/src/backend/kzgrs.rs
  nomos-services/mempool/src/da/service.rs
  nomos-services/mempool/src/lib.rs
  tests/src/common/da.rs
  tests/src/tests/da/disperse.rs
Labels: da

#1130 feat(blend): separate unhealthy conn tolerance from malicious tolerance
  nomos-blend/core/src/conn_maintenance.rs
  nomos-blend/network/src/lib.rs
Labels: blend

#1134 fix: Return mempool error when AddItem fails
  nomos-services/mempool/src/da/service.rs
  nomos-services/mempool/src/tx/service.rs
Labels: Mempool

#1089 chore: Improve README
  README.md
Labels: documentation

#1043 feature(consensus): Recovery
  consensus/cryptarchia-engine/src/lib.rs
  ledger/nomos-ledger/src/lib.rs
  nomos-services/cryptarchia-consensus/src/leadership.rs
  nomos-services/cryptarchia-consensus/src/lib.rs
  nomos-services/cryptarchia-consensus/src/relays.rs
  nomos-services/cryptarchia-consensus/src/states.rs
Labels: consensus

#1143 fix(DA): Sampling behaviour lost requests
  nomos-da/network/core/src/protocols/sampling/behaviour.rs
  nomos-da/network/core/src/swarm/common/monitor.rs
  nomos-da/network/messages/src/sampling.rs
  nomos-services/data-availability/sampling/src/backend/kzgrs.rs
  tests/src/topology/configs/da.rs
  tests/src/topology/mod.rs
Labels: network, da

#1152 chore: Update nomos image to match repository name
  compose.static.yml
Labels: testnet

#1150 ci: Use locked dependency versions for cargo binstall
  Dockerfile
  ci/Dockerfile
  testnet/Dockerfile
Labels: ci

#1138 feat(DA): request shares HTTP API
  clients/common-http-client/Cargo.toml
  clients/common-http-client/src/lib.rs
  clients/executor-http-client/Cargo.toml
  clients/executor-http-client/src/lib.rs
  nodes/nomos-executor/src/api/backend.rs
  nodes/nomos-node/src/api/backend.rs
  nodes/nomos-node/src/api/handlers.rs
  nodes/nomos-node/src/api/paths.rs
  nomos-core/chain-defs/src/da/blob/mod.rs
  nomos-da/kzgrs-backend/src/common/share.rs
  nomos-da/network/messages/src/http/da.rs
  nomos-services/api/Cargo.toml
  nomos-services/api/src/http/da_shares.rs
  nomos-services/api/src/http/mod.rs
  nomos-services/data-availability/verifier/src/storage/adapters/rocksdb.rs
  tests/Cargo.toml
  tests/src/tests/da/api.rs
Labels: da

#1182 fix: Use bytemuck_derive 1.8.1 for risc0
  nomos-core/risc0_proofs/bundle_balance/Cargo.toml
  nomos-core/risc0_proofs/covenant_nop/Cargo.toml
  nomos-core/risc0_proofs/proof_of_leadership/Cargo.toml
  nomos-core/risc0_proofs/ptx/Cargo.toml
Labels: ci

#1192 chore: Update risc0 to v2.0.0
  .github/actions/install-risc0/action.yml
  Cargo.toml
  Dockerfile
  nomos-core/risc0_proofs/Cargo.toml
  nomos-core/risc0_proofs/bundle_balance/Cargo.toml
  nomos-core/risc0_proofs/covenant_nop/Cargo.toml
  nomos-core/risc0_proofs/proof_of_leadership/Cargo.toml
  nomos-core/risc0_proofs/ptx/Cargo.toml
  testnet/Dockerfile
Labels: ci

#1194 chore: Use cargo install for rzup
  .github/actions/install-risc0/action.yml
Labels: ci

#1156 feature(bounded-duration): Integrate with configs' durations
  Cargo.toml
  consensus/cryptarchia-engine/Cargo.toml
  consensus/cryptarchia-engine/src/lib.rs
  consensus/cryptarchia-engine/src/time.rs
  dependencies_graph.dot
  nodes/nomos-node/config.yaml
  nomos-blend/core/Cargo.toml
  nomos-blend/core/src/conn_maintenance.rs
  nomos-blend/core/src/message_blend/temporal.rs
  nomos-da/network/core/Cargo.toml
  nomos-da/network/core/src/swarm/common/monitor.rs
  nomos-services/blend/Cargo.toml
  nomos-services/blend/src/lib.rs
  nomos-services/cryptarchia-consensus/Cargo.toml
  nomos-services/data-availability/dispersal/Cargo.toml
  nomos-services/data-availability/dispersal/src/backend/kzgrs.rs
  nomos-services/time/Cargo.toml
  nomos-services/time/src/backends/ntp/async_client.rs
  nomos-services/time/src/backends/ntp/mod.rs
  nomos-services/time/src/lib.rs
  nomos-utils/Cargo.toml
  nomos-utils/src/bounded_duration.rs
  testnet/cfgsync.yaml
  testnet/cfgsync/Cargo.toml
  testnet/cfgsync/src/client.rs
  testnet/cfgsync/src/lib.rs
  testnet/cfgsync/src/server.rs
  tests/src/nodes/executor.rs
  tests/src/nodes/validator.rs
  tests/src/topology/configs/da.rs
Labels: consensus, blend

#1197 feature(pre-commit): Dependency graph hook
  .pre-commit-config.yaml
  hooks/generate-dependency-graph.sh
Labels: ci

#1196 chore: Update dockerfiles to use rzup
  .github/actions/install-risc0/action.yml
  Dockerfile
  ci/Dockerfile
  testnet/Dockerfile
Labels: ci

#1190 chore(cryptarchia-consensus): Add time relay to consensus relays
  nomos-services/blend/src/lib.rs
  nomos-services/cryptarchia-consensus/src/lib.rs
  nomos-services/cryptarchia-consensus/src/relays.rs
Labels: dependencies
