Repository logos-co/nomos, pull requests merged in 2025-01, with the labels that each got.

#983 fix: Temporarily downgrade cargo-binstall to 1.10.19
  Dockerfile
  ci/Dockerfile
  testnet/Dockerfile
Labels: dependencies

#979 fix(blend): maintain malicious peers continously
  nomos-blend/core/src/conn_maintenance.rs
Labels: bug, blend

#981 Kms service
  Cargo.toml
  nomos-services/key-management-system/Cargo.toml
  nomos-services/key-management-system/src/backend/mod.rs
  nomos-services/key-management-system/src/lib.rs
  nomos-services/key-management-system/src/secure_key.rs
Labels: kms

#971 chore(dependencies): Update Overwatch deps and related code
  nodes/nomos-executor/Cargo.toml
  nodes/nomos-node/Cargo.toml
  nomos-services/api/Cargo.toml
  nomos-services/api/src/lib.rs
  nomos-services/blend/Cargo.toml
  nomos-services/blend/src/lib.rs
  nomos-services/cryptarchia-consensus/Cargo.toml
  nomos-services/cryptarchia-consensus/src/lib.rs
  nomos-services/data-availability/dispersal/Cargo.toml
  nomos-services/data-availability/dispersal/src/lib.rs
  nomos-services/data-availability/indexer/Cargo.toml
  nomos-services/data-availability/indexer/src/lib.rs
  nomos-services/data-availability/network/Cargo.toml
  nomos-services/data-availability/network/src/lib.rs
  nomos-services/data-availability/sampling/Cargo.toml
  nomos-services/data-availability/sampling/src/lib.rs
  nomos-services/data-availability/tests/Cargo.toml
  nomos-services/data-availability/verifier/Cargo.toml
  nomos-services/data-availability/verifier/src/lib.rs
  nomos-services/mempool/Cargo.toml
  nomos-services/mempool/src/da/service.rs
  nomos-services/mempool/src/tx/service.rs
  nomos-services/network/Cargo.toml
  nomos-services/network/src/lib.rs
  nomos-services/storage/Cargo.toml
  nomos-services/storage/src/lib.rs
  nomos-services/system-sig/Cargo.toml
  nomos-services/system-sig/src/lib.rs
  nomos-services/tracing/Cargo.toml
  nomos-services/tracing/src/lib.rs
  tests/Cargo.toml
Labels: dependencies

#984 chore(da): Remove protobuf files.
  Dockerfile
  ci/Dockerfile
  nomos-da/network/messages/proto/common.proto
  nomos-da/network/messages/proto/dispersal.proto
  nomos-da/network/messages/proto/replication.proto
  nomos-da/network/messages/proto/sampling.proto
  shell.nix
  testnet/Dockerfile
Labels: da

#996 fix(ci): Update checkout actions version
  .github/workflows/build-test.yml
  .github/workflows/codecov.yml
Labels: ci

#975 feature(node-recovery): Implement Overwatch recovery POC
  Cargo.toml
  nodes/nomos-executor/Cargo.toml
  nodes/nomos-node/Cargo.toml
  nomos-services/api/Cargo.toml
  nomos-services/blend/Cargo.toml
  nomos-services/cryptarchia-consensus/Cargo.toml
  nomos-services/data-availability/dispersal/Cargo.toml
  nomos-services/data-availability/indexer/Cargo.toml
  nomos-services/data-availability/network/Cargo.toml
  nomos-services/data-availability/sampling/Cargo.toml
  nomos-services/data-availability/tests/Cargo.toml
  nomos-services/data-availability/verifier/Cargo.toml
  nomos-services/mempool/Cargo.toml
  nomos-services/network/Cargo.toml
  nomos-services/storage/Cargo.toml
  nomos-services/system-sig/Cargo.toml
  nomos-services/tracing/Cargo.toml
  nomos-services/utils/Cargo.toml
  nomos-services/utils/src/lib.rs
  nomos-services/utils/src/overwatch/mod.rs
  nomos-services/utils/src/overwatch/recovery.rs
  nomos-services/utils/src/traits.rs
  nomos-utils/Cargo.toml
  tests/Cargo.toml
Labels: node

#977 feature(packaging): Proof of concept
  .github/actions/install-dependencies/action.yml
  .github/actions/install-risc0/action.yml
  .github/workflows/packaging.yml
  .gitignore
  Cargo.toml
  nodes/nomos-node/resources/icons/512x512.png
  nodes/nomos-node/resources/icons/icon.ico
  nomos-bundler/Cargo.toml
  nomos-bundler/README.md
  nomos-bundler/nomos-node/bundle.rs
  nomos-bundler/src/lib.rs
  nomos-bundler/src/utils.rs
  nomos-cli/Cargo.toml
  nomos-libp2p/Cargo.toml
  nomos-services/data-availability/verifier/Cargo.toml
Labels: ci

#995 chore(service-status): Update deps to integrate Overwatch's service status
  nodes/nomos-executor/Cargo.toml
  nodes/nomos-node/Cargo.toml
  nomos-services/api/Cargo.toml
  nomos-services/blend/Cargo.toml
  nomos-services/cryptarchia-consensus/Cargo.toml
  nomos-services/data-availability/dispersal/Cargo.toml
  nomos-services/data-availability/indexer/Cargo.toml
  nomos-services/data-availability/network/Cargo.toml
  nomos-services/data-availability/sampling/Cargo.toml
  nomos-services/data-availability/tests/Cargo.toml
  nomos-services/data-availability/verifier/Cargo.toml
  nomos-services/mempool/Cargo.toml
  nomos-services/network/Cargo.toml
  nomos-services/storage/Cargo.toml
  nomos-services/system-sig/Cargo.toml
  nomos-services/tracing/Cargo.toml
  tests/Cargo.toml
Labels: dependencies

#992 feat(kms): add the preload backend
  nomos-services/key-management-system/Cargo.toml
  nomos-services/key-management-system/src/backend/mod.rs
  nomos-services/key-management-system/src/backend/preload.rs
  nomos-services/key-management-system/src/keys/ed25519.rs
  nomos-services/key-management-system/src/keys/mod.rs
  nomos-services/key-management-system/src/lib.rs
  nomos-services/key-management-system/src/secure_key.rs
Labels: kms
